### ISSUE TITLE
Filezilla new version not so new

### ISSUE THREAD

**Issue by Thomgi** [autopkg/scriptingosx-recipes#10]
Hi,

Each time autopkgr run, it send me a notification that say :

```
New software available for testing:

NAME	VERSION
FileZilla_3.14.1_macosx-x86.app.tar	Unknown version
```

But it's the same version as already found (and already in my JSS).
Could you help me to fix that and understand why ?

**Comment by scriptingosx** [comment]
Since my Firefox recipes are base on the Firefox recipes in autopkg/recipes you will have to look there. It seems as if Mozilla has changed those URLs recently and then the recipes were updates a few days ago.

**Comment by gregneagle** [comment]
? FileZilla != Firefox

**Comment by scriptingosx** [comment]
Thanks for catching that Greg. Not sure why AutoPkgr keeps reporting this though. As far as I can tell my recipe reports the version correctly. 

```
armin$ autopkg run Filezilla.pkg
Processing Filezilla.pkg...

The following packages were built:
    Identifier    Version  Pkg Path                                                                                       
    ----------    -------  --------                                                                                       
    de.filezilla  3.14.1   /Users/armin/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.FileZilla/FileZilla-3.14.1.pkg  

The following new items were downloaded:
    Download Path                                                                                                               
    -------------                                                                                                               
    /Users/armin/Library/AutoPkg/Cache/com.github.scriptingosx.pkg.FileZilla/downloads/FileZilla_3.14.1_macosx-x86.app.tar.bz2  
```

I do not use AutoPkgr, though. You will have to ask them.Are you on the latest stable AutoPKG and AutoPkgr version?

**Comment by gregneagle** [comment]
If the recipe results in a new download even if the actual item is unchanged, Autopkgr will notify, which might be considered a design flaw in Autopkgr. But that doesn't seem to be the problem Thomgi is seeing.

**Comment by gregneagle** [comment]
https://github.com/lindegroup/autopkgr/issues/184

**Comment by Thomgi** [comment]
Hi, sorry for the delay and thank for the answers.

The main question is : why autopkg download again something that already downloaded ?

As Greg says, the consequence is that autopkgr notify me that a new version software is available, which is "normal" because of autopkg believe in needed of download new item.

That's why I though an problem with the recipe, but maybe I'm wrong.

**Comment by gregneagle** [comment]
autopkg may be downloading an item again because the web server is not returning data in the headers that allows autopkg to determine the item it has already is the same as the one on the web server. Many web servers do this, but not all. We have no control over the configuration of the web servers developers choose to host their downloads.

As for Autopkgr notifying you about repeated downloads, that's an issue you should raise with the Autopkgr developers. (But check the existing issues first!)
