### ISSUE TITLE
Unable to add git

### ISSUE THREAD

**Issue by dingerkingh** [autopkg/scriptingosx-recipes#11]
`autopkg repo-add scriptingosx-recipes` does not work 

ERROR: fatal: Not a git repository (or any of the parent directories): .git

What am I doing wrong?

**Comment by scriptingosx** [comment]
Not sure. I just attempted the repo-add on a clean system and it works for me. There may be left over git files in the AutoPkg/RecipeRepos folder or the AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes folder. Delete any com.github.autopkg.scriptingosx folders in your Recipe search path.

**Comment by gregneagle** [comment]
...and: can you `autopkg repo-add` any other repo? Is your issue actually limited to scriptingosx-recipes?

**Comment by dingerkingh** [comment]
I can add other repos - just not scriptingosx. I'll try deleting those files.

**Comment by dingerkingh** [comment]
That fixed it. Thank you!
