### ISSUE TITLE
FileZilla.jss version number isn't parsing correctly.

### ISSUE THREAD

**Issue by SmithersJr** [autopkg/scriptingosx-recipes#13]
Notification shows this:
FileZilla_3.15.0.1_macosx-x86.app.tar	Unknown version

So, AutoPkgr keeps downloading it.

**Comment by scriptingosx** [comment]
Cannot recreate the problem, it works for me. Have you tried (a) deleting this recipe's folder in the Cache? and (b) updating the recipe repositories?

**Comment by SmithersJr** [comment]
Hmm, looks like it started working again sometime yesterday. If I see more
problems, I'll do some more trouble-shooting.
