### ISSUE TITLE
WhatsApp download changed from .zip to .dmg

### ISSUE THREAD

**Issue by oucsaw** [autopkg/scriptingosx-recipes#20]
WhatsApp seem to have changed from a .zip download to a .dmg download in the last day or so:

 ```
 host:tmp user$ curl --location -O https://web.whatsapp.com/desktop/mac/files/WhatsApp.zip
 <snip>
 host:tmp user$ curl --location -O https://web.whatsapp.com/desktop/mac/files/WhatsApp.dmg
 <snip>
 host:tmp user$ diff WhatsApp.zip WhatsApp.dmg
 host:tmp user$ shasum   WhatsApp.zip WhatsApp.dmg
 70d54863582bc38b8ae67b6bee96b0d37e5a68dc  WhatsApp.zip
 70d54863582bc38b8ae67b6bee96b0d37e5a68dc  WhatsApp.dmg
 ```

Attached is a compressed patch that will (hopefully) fix the WhatsApp.download.recipe and WhatsApp.munki.recipe; however changing the download file impacts on the 
WhatsApp.install.recipe and WhatsApp.package.recipe, and unfortunately we don't have the resources to test any changes to these properly (and don't want to introduce a breaking change).

[whatsapp.patch.zip](https://github.com/autopkg/scriptingosx-recipes/files/585703/whatsapp.patch.zip)

**Comment by scriptingosx** [comment]
Thanks for pointing this out. I had to re-work most of the recipes.
https://github.com/autopkg/scriptingosx-recipes/commit/b113525de2d364182b96b9b78c8e212085e100e6
