### ISSUE TITLE
Removed Audacity.download due to TOS violation

### ISSUE THREAD

**Issue by timsutton** [autopkg/scriptingosx-recipes#21]
Audacity's download from fosshub is now clearly in violation of their TOS, so I've removed my Audacity.download recipe and made the Audacity.munki recipe I maintain require the `--pkg` argument so that a user may supply their own download. This just involved changing `%pathname%` to `%PKG%` and adding a `PackageRequired` argument so that it's clearer to users how the recipe must be used.

Since you've also got Audacity recipes that ultimately derive from Audacity.download (or are a copy of it), I'm opening this issue on this and a couple other repos.

More details:

https://www.fosshub.com/tos.html

https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub
http://forum.audacityteam.org/viewtopic.php?f=50&t=94040
https://www.reddit.com/r/sysadmin/comments/5g5npg/fosshub_message_for_chocolatey_please_stop_with/

Keeping the fosshub scraping working for this recipe has been a chore and Audacity is rarely ever updated, so I can't say I don't prefer this approach anyway.

Since there also seems to be duplication across a few of @homebysix, @scriptingosx and @novaksam's recipes it might also be a good time to evaluate whether any recipes could be removed in favour of one or another.

**Comment by scriptingosx** [comment]
I pushed the change to `Audacity.pkg`. Child recipes from @jazzace, @homebysix, @patgmac please test!

**Comment by homebysix** [comment]
Audacity.jss, which uses Audacity.pkg as a parent, seems to work fine after the change. I've added some extra information to the description of that recipe.

**Comment by cwhits** [comment]
Has anyone contacted FossHub about letting AutoPkg scrape their site? It seems like AutoPkg would definitely fit their exceptions because unlike Chocolately, we download once then distribute using Munki, JAMF, etc.

https://www.fosshub.com/tos.html
```
Exceptions
If you wish to retrieve files from www.fosshub.com using an automated tool or script with the purpose of redistributing them on your internal network, download server, download mirror, CDN or any other similar service we might allow you to do this under the following conditions:
- Inform us about your intention before any attempt to interact with our website. If possible, provide us a sample of your code/tool to see how it is designed to work with our system.
- If you are the representative of a school, University or any other educational institution.
- If you represent a non-profit organization focused on education, health or any other worthy cause.
- A company that wishes to retrieve files from us but use its own replication system.
```

**Comment by scriptingosx** [comment]
@timsutton had the original download recipe. He has more information here: https://github.com/autopkg/timsutton-recipes/commit/6d76c7ff3255639bc4d03209ce052f4d853f2d39
