### ISSUE TITLE
Python3.munki recipe fails due to PkgPayloadUnpacker

### ISSUE THREAD

**Issue by sheagcraig** [autopkg/scriptingosx-recipes#33]
So I realize that the Python3 recipe changed as a result of a PR I made, but it hadn't been working for me.

What I realized is that to take the Python3 package apart, I used PkgPayloadUnpacker, and mistakenly tried to create multiple nested directories in one go with the destination_path.

I have a PR in for AutoPkg to make all of the core processors use `os.makedirs` instead of `os.mkdir` to make this work, but in the meantime, the recipe will fail.

**Comment by sheagcraig** [comment]
https://github.com/autopkg/autopkg/pull/401

**Comment by scriptingosx** [comment]
not sure if this is still relevant. Python3.pkg works for me. Closing for now
