### ISSUE TITLE
EraseInstaller RecipeIdentifier ist missing github in name.

### ISSUE THREAD

**Issue by Bretterteig** [autopkg/scriptingosx-recipes#36]
Munki and Jamf recipe require 
com.github.scriptingosx.download.EraseInstall

Download recipe has identifier
com.scriptingosx.download.EraseInstall

**Comment by scriptingosx** [comment]
Thank you! 

Should be fixed in https://github.com/autopkg/scriptingosx-recipes/commit/5d6576ccad5707b64eb78c63fb3d8fe331296151
