### ISSUE TITLE
VMWare Horizon Client v5 not picked up by recipe

### ISSUE THREAD

**Issue by smashism** [autopkg/scriptingosx-recipes#38]
Howdy! I'm sure VMware changed something with the download but version 5 is available of VMware Horizon Client and the recipe as it currently stands is not downloading the new version.

**Comment by scriptingosx** [comment]
Should be in https://github.com/autopkg/scriptingosx-recipes/commit/f122a92cf5813b67b5748da9061fb0bc406c179c

You need to check if you have the old URL in your override, otherwise the new one won't take effect.

**Comment by smashism** [comment]
Looks like the latest commit fixes the download. Thanks!
