### ISSUE TITLE
Shellcheck.munki fails

### ISSUE THREAD

**Issue by lashomb** [autopkg/scriptingosx-recipes#46]
The following recipes failed:
    Shellcheck.munki
        MunkiPkginfoMerger requires missing argument additional_pkginfo

**Comment by scriptingosx** [comment]
fixed in https://github.com/autopkg/scriptingosx-recipes/commit/326acf1f258aa0c6a38d69c10871c2b7433dd9b0

**Comment by scriptingosx** [comment]
Thanks!
