### ISSUE TITLE
Error in local.munki.Shellcheck: Processor: XZUnarchiver: Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lashomb** [autopkg/scriptingosx-recipes#48]
Seeing this now, is there a prereq to use the `XZUnarchiver` processor that I might be missing?

```The following recipes failed:
    Shellcheck.munki
        Error in local.munki.Shellcheck: Processor: XZUnarchiver: Error: [Errno 2] No such file or directory```

**Comment by flammable** [comment]
@lashomb Hey, how did you fix this? I'm having the same issue - I just created my override, but it fails to run successfully.

**Comment by flammable** [comment]
I managed to solve this but ran into more errors. I'll open a new issue.
