### ISSUE TITLE
Issues with Shellcheck.munki

### ISSUE THREAD

**Issue by flammable** [autopkg/scriptingosx-recipes#54]
Hey Armin! I'm running into some difficulty with Shellcheck.munki, and figured I'd post a new issue.

The first problem I encountered was this one, mentioned in #48:

```
The following recipes failed:
    local.munki.Shellcheck
        Error in local.munki.Shellcheck: Processor: XZUnarchiver: Error: [Errno 2] No such file or directory: '/Users/user/Library/AutoPkg/RecipeOverrides/xz': '/Users/user/Library/AutoPkg/RecipeOverrides/xz'
```

I managed to fix this by adding a symlink:

`ln -s /Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes/Shellcheck/xz /Users/user/Library/AutoPkg/RecipeOverrides/`

However, after that, I encountered this error:

```
The following recipes failed:
    local.munki.Shellcheck
        Error in local.munki.Shellcheck: Processor: Unarchiver: Error: Unarchiving /Users/user/Library/AutoPkg/Cache/local.munki.Shellcheck/downloads/shellcheck-stable.darwin.x86_64.tar with tar failed: tar: Error opening archive: Failed to open '/Users/user/Library/AutoPkg/Cache/local.munki.Shellcheck/downloads/shellcheck-stable.darwin.x86_64.tar'
```

My AutoPkg machine is still running macOS 10.13.6 for the moment, so I don't know if that's the culprit here. I've held off on upgrading it, because I can't actually get to campus to troubleshoot if it doesn't come back online.

If it's not the OS, is there anything else I can try? Thanks!

**Comment by arubdesu** [comment]
Shellcheck moved hosting of their builds to github, as they say in the unpacked README

> You are downloading ShellCheck from an outdated URL!
> Please update to the new URL:
> https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.darwin.x86_64.tar.xz
> For more information, see:
> https://github.com/koalaman/shellcheck/issues/1871
> PS: Sorry for breaking your build :(

**Comment by flammable** [comment]
Ah, good catch, Allister. Thanks!

I see there's a couple of pull requests from @octomike, so I'll wait for those to be merged and try again.
