### ISSUE TITLE
AppleCreativity Packages

### ISSUE THREAD

**Issue by bengreeno** [autopkg/scriptingosx-recipes#7]
I'm not sure if its a problem on my end, but it seems like a dummy receipt is no longer created for the MAS apps. If I use GenericMASApp.pkg.recipe through Terminal and manually change the app name then the dummy receipt is present. 

Is there a way to have the individual MAS app recipes keep the dummy receipt as opposed to deleting it?

Thanks!

**Comment by scriptingosx** [comment]
I am not sure what you are trying to do.

But for every application you want to package you should create its own an separate override and change the variables accordingly.

**Comment by bengreeno** [comment]
I just wanted to confirm that this is expected behavior:

I’m using AutoPkgr to download Pages.pkg.recipe, but the _MASReceipt has been deleted. Was this always the case? For some reason I thought that a dummy receipt was created. 

If I’m wrong then I’m the dummy :) Thanks for your time!

**Comment by scriptingosx** [comment]
the default setting for MASReceipt in the recipes is 'delete' mainly because that is what I use. If you need to change that, then create an override for the recipe with you own setting.

**Comment by bengreeno** [comment]
Wonderful! Thanks for following up.


—
Ben Greeno | bengreeno@me.com | 847.630.4216
